kind: pipeline
name: qt-5.15

steps:
- name: cmake
  image: ghcr.io/nextcloud/continuous-integration-client:client-5.15-4
  volumes:
    - name: build
      path: /drone/build
  commands:
    - cd /drone/build
    - cmake -DCMAKE_C_COMPILER=gcc-10 -DCMAKE_CXX_COMPILER=g++-10 -DCMAKE_BUILD_TYPE=Debug -DQUICK_COMPILER=ON -DBUILD_UPDATER=ON -DBUILD_TESTING=1 -DECM_ENABLE_SANITIZERS=address -DCMAKE_CXX_FLAGS=-Werror ../src
- name: compile
  image: ghcr.io/nextcloud/continuous-integration-client:client-5.15-4
  volumes:
    - name: build
      path: /drone/build
  commands:
    - cd /drone/build
    - make -j$(nproc)
- name: test
  image: ghcr.io/nextcloud/continuous-integration-client:client-5.15-4
  volumes:
    - name: build
      path: /drone/build
  commands:
    - cd /drone/build
    - useradd -m -s /bin/bash test
    - chown -R test:test .
    - su -c 'ASAN_OPTIONS=detect_leaks=0 xvfb-run ctest --output-on-failure' test

volumes:
- name: build
  temp: {}

trigger:
  branch:
    - master
    - stable-*
  event:
    - pull_request
    - push