version: '{build}-{branch}'

image: Visual Studio 2019

branches:
  only:
    - master

clone_depth: 1

init:
- ps: |
    function crafttests() {
        craft --test nextcloud-client
    }

install:
- ps: |
    #use cmd to silence powershell behaviour for stderr
    Set-ExecutionPolicy -Scope CurrentUser RemoteSigned
    iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/KDE/craft/master/setup/install_craft.ps1'))
    & C:\CraftRoot\craft\craftenv.ps1
    craft --add-blueprint-repository [git]https://github.com/nextcloud/desktop-client-blueprints.git
    craft nextcloud-client
    craft nsis
    choco install opencppcoverage
- set PATH=C:\Program Files\OpenCppCoverage;%PATH%

build_script:
- ps: |
    craft --compile nextcloud-client

test_script:
- ps: |
    crafttests

environment:
    matrix:
    - TARGET: windows-msvc2019_64-cl
