version: '{build}-{branch}'

image: Visual Studio 2019

branches:
  only:
    - master

clone_depth: 1

init:
- ps: |
    function craft() {
        cmd /C "echo %PATH%"
        & "C:\Python39-x64\python.exe" "C:\CraftMaster\CraftMaster\CraftMaster.py" --verbose --config "$env:APPVEYOR_BUILD_FOLDER\appveyor.ini" --variables "APPVEYOR_BUILD_FOLDER=$env:APPVEYOR_BUILD_FOLDER" --target $env:TARGET -c $args
        if($LASTEXITCODE -ne 0) {exit $LASTEXITCODE}
    }
    function runTests() {
        echo "Inside crafttests()"
        cmd /C "echo %PATH%"
        cd C:/CraftMaster/windows-msvc2019_64-cl/build/nextcloud-client/work/build/bin
        $LASTEXITCODE = 0
        .\IconUtilsTest.exe
        .\ThemeTest.exe
        cd ~
        echo $LASTEXITCODE
        if($LASTEXITCODE -ne 0) {exit $LASTEXITCODE}
    }

install:
- ps: |
    #use cmd to silence powershell behaviour for stderr
    & cmd /C "git clone -q --depth=1 https://invent.kde.org/packaging/craftmaster.git C:\CraftMaster\CraftMaster 2>&1"
    craft --add-blueprint-repository [git]https://github.com/nextcloud/desktop-client-blueprints.git
    craft craft
    craft --install-deps nextcloud-client
    craft nsis
    choco install opencppcoverage

build_script:
- ps: |
    craft --src-dir $env:APPVEYOR_BUILD_FOLDER nextcloud-client

test_script:
- ps: |
    runTests

environment:
    matrix:
    - TARGET: windows-msvc2019_64-cl
