version: '{build}-{branch}'

image: Visual Studio 2019

branches:
  only:
    - master

clone_depth: 1

init:
- ps: |
    function craft() {
        & "C:\Python39-x64\python.exe" "C:\CraftMaster\CraftMaster\CraftMaster.py" --verbose --config "$env:APPVEYOR_BUILD_FOLDER\appveyor.ini" --variables "APPVEYOR_BUILD_FOLDER=$env:APPVEYOR_BUILD_FOLDER" --target $env:TARGET -c $args
        if($LASTEXITCODE -ne 0) {exit $LASTEXITCODE}
    }
    function crafttests() {
        cmd /C "echo %PATH%"
        cd C:/CraftMaster/windows-msvc2019_64-cl/build/nextcloud-client/work/build
        & OpenCppCoverage.exe --modules $env:APPVEYOR_BUILD_FOLDER --excluded_modules="C:\Program Files\CMake\bin\ctest.exe" --quiet --export_type cobertura:test_coverage.xml --cover_children -- C:\CraftMaster\windows-msvc2019_64-cl\dev-utils\bin\ctest.exe -VV --output-on-failure --timeout 300 -j 2 -c $env:TARGET
        # & "C:\Python39-x64\python.exe" "C:\CraftMaster\CraftMaster\CraftMaster.py" --verbose --config "$env:APPVEYOR_BUILD_FOLDER\appveyor.ini" --variables "APPVEYOR_BUILD_FOLDER=$env:APPVEYOR_BUILD_FOLDER" --target $env:TARGET -c $args
    }

install:
- ps: |
    #use cmd to silence powershell behaviour for stderr
    & cmd /C "git clone -q --depth=1 https://invent.kde.org/packaging/craftmaster.git C:\CraftMaster\CraftMaster 2>&1"
    craft --add-blueprint-repository [git]https://github.com/nextcloud/desktop-client-blueprints.git
    craft craft
    craft --install-deps nextcloud-client
    # craft nsis
    choco install opencppcoverage
- set PATH=C:\Program Files\OpenCppCoverage;C:\CraftMaster\windows-msvc2019_64-cl\bin;%PATH%

build_script:
- ps: |
    craft --src-dir $env:APPVEYOR_BUILD_FOLDER nextcloud-client

test_script:
- ps: |
    crafttests --test --src-dir $env:APPVEYOR_BUILD_FOLDER nextcloud-client

environment:
    matrix:
    - TARGET: windows-msvc2019_64-cl
