# SPDX-FileCopyrightText: 2025 Nextcloud GmbH and Nextcloud contributors
# SPDX-License-Identifier: GPL-2.0-or-later
version = 1
SPDX-PackageName = "desktop"
SPDX-PackageSupplier = "Nextcloud <info@nextcloud.com>"
SPDX-PackageDownloadLocation = "https://github.com/nextcloud/desktop"

[[annotations]]
path = ["translations/*"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2012 ownCloud Inc. and ownCloud translators, 2018 Nextcloud GmbH and Nextcloud translators"
SPDX-License-Identifier = "GPL-2.0-or-later"

[[annotations]]
path = ["admin/win/nsi/l10n/*"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2013 ownCloud Inc. and ownCloud translators, 2020 Nextcloud GmbH and Nextcloud translators"
SPDX-License-Identifier = "GPL-2.0-or-later"

[[annotations]]
path = ["nextcloud.client-desktop/*"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2022 Nextcloud GmbH and Nextcloud translators"
SPDX-License-Identifier = "GPL-2.0-or-later"

[[annotations]]
path = ["doc/images/mac-share.png"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2016 ownCloud GmbH"
SPDX-License-Identifier = "CC-BY-3.0"

[[annotations]]
path = ["doc/images/checksums/client-activity.png", "doc/images/checksums/testing-checksums.png", "doc/images/create_debug_archive.png", "doc/images/dev/desktop-development-with-cpp.png", "doc/images/dev/path.png", "doc/images/dev/visual-studio-installer.png", "doc/images/folderwizard_local.png", "doc/images/folderwizard_remote.png", "doc/images/general_settings_folder_context_menu.png", "doc/images/icon-error.png", "doc/images/icon-information.png", "doc/images/icon-offline.png", "doc/images/icon-paused.png", "doc/images/icon-syncing.png", "doc/images/icon.png", "doc/images/ignored_files_editor.png", "doc/images/log_output_window.png", "doc/images/macosvfs-file-locking.png", "doc/images/macosvfs-file-sharing.png", "doc/images/macosvfs-finder-sidebar.png", "doc/images/macosvfs-settings.png", "doc/images/macosvfs-sync-status-icons.png", "doc/images/main_dialog.png", "doc/images/main_dialog_christine.png", "doc/images/open-share-dialog.png", "doc/images/save_log_file.png", "doc/images/set-user-status-menu.png", "doc/images/set-user-status.png", "doc/images/settings_general.png", "doc/images/settings_network.png", "doc/images/settingsdialog.png", "doc/images/setup/confirm.png", "doc/images/setup/remove.png", "doc/images/setup/wizard.png", "doc/images/share-dialog-view-profile.png", "doc/images/share_context_menu.png", "doc/images/share_dialog.png", "doc/images/status_feature_example.png", "doc/images/sync-state-paused.png", "doc/images/sync-state-synced.png", "doc/images/sync-state-syncing.png", "doc/images/sync-state-warnings.png", "doc/images/traymenu.png", "doc/images/unified-search-events.png", "doc/images/unified-search-files.png", "doc/images/unified-search-talk.png", "doc/images/user-account-options.png", "doc/images/user_status-selector_dialog.png", "doc/images/user_status_selector_main_dialog.png", "doc/images/vfs_context_menu_options.png", "doc/images/vfs_hydration_progress_bar.png", "doc/images/wizard_advanced.png", "doc/images/wizard_flow2.png", "doc/images/wizard_setup.png", "doc/images/wizard_welcome.png"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2016 Nextcloud GmbH and Nextcloud contributors"
SPDX-License-Identifier = "CC-BY-3.0"

[[annotations]]
path = ["doc/architecture.rst", "doc/building.rst", "doc/glossary.rst", "doc/index.rst", "doc/troubleshooting.rst"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2012 ownCloud GmbH, 2018 Nextcloud GmbH and Nextcloud contributors"
SPDX-License-Identifier = "CC-BY-3.0"

[[annotations]]
path = ["doc/advancedusage.rst", "doc/conffile.rst", "doc/introduction.rst", "doc/options.rst", "doc/visualtour.rst"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2013 ownCloud GmbH, 2018 Nextcloud GmbH and Nextcloud contributors"
SPDX-License-Identifier = "CC-BY-3.0"

[[annotations]]
path = ["doc/massdeploymentcommandline.rst"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2013 ownCloud GmbH, 2023 Nextcloud GmbH and Nextcloud contributors"
SPDX-License-Identifier = "CC-BY-3.0"

[[annotations]]
path = ["doc/autoupdate.rst", "doc/faq.rst", "doc/installing.rst", "doc/navigating.rst"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2014 ownCloud GmbH, 2018 Nextcloud GmbH and Nextcloud contributors"
SPDX-License-Identifier = "CC-BY-3.0"

[[annotations]]
path = ["doc/lowdiskspace.rst"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2016 ownCloud GmbH, 2018 Nextcloud GmbH and Nextcloud contributors"
SPDX-License-Identifier = "CC-BY-3.0"

[[annotations]]
path = ["doc/envvars.rst"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2017 ownCloud GmbH, 2025 Nextcloud GmbH and Nextcloud contributors"
SPDX-License-Identifier = "CC-BY-3.0"

[[annotations]]
path = ["doc/conflicts.rst"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2018 ownCloud GmbH, 2020 Nextcloud GmbH and Nextcloud contributors"
SPDX-License-Identifier = "CC-BY-3.0"

[[annotations]]
path = [".tx/config"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2018 Nextcloud GmbH and Nextcloud contributors"
SPDX-License-Identifier = "GPL-2.0-or-later"

[[annotations]]
path = ["doc/nextcloudcmd.rst"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2018 Nextcloud GmbH and Nextcloud contributors"
SPDX-License-Identifier = "CC-BY-3.0"

[[annotations]]
path = ["doc/options-cmd.rst", "doc/wizardaccountsetupcommandline.rst"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2023 Nextcloud GmbH and Nextcloud contributors"
SPDX-License-Identifier = "CC-BY-3.0"

[[annotations]]
path = ["doc/macosvfs.rst"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 Nextcloud GmbH and Nextcloud contributors"
SPDX-License-Identifier = "CC-BY-3.0"

[[annotations]]
path = ["man/index.rst"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2017 ownCloud GmbH"
SPDX-License-Identifier = "CC-BY-3.0"

[[annotations]]
path = ["man/nextcloud.1.rst", "man/nextcloudcmd.1.rst"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2017 ownCloud GmbH, 2018 Nextcloud GmbH and Nextcloud contributors"
SPDX-License-Identifier = "CC-BY-3.0"

[[annotations]]
path = [".tx/nextcloud.client-desktop/*_translation", "theme/*/state-error.svg", "theme/*/state-info.svg", "theme/*/state-offline.svg", "theme/*/state-ok.svg", "theme/*/state-pause.svg", "theme/*/state-sync.svg", "theme/*/state-warning.svg"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2018 Nextcloud GmbH and Nextcloud contributors"
SPDX-License-Identifier = "GPL-2.0-or-later"

[[annotations]]
path = ["theme/colored/user-status-away.svg", "theme/colored/user-status-dnd.svg", "theme/colored/user-status-invisible.svg", "theme/colored/user-status-online.svg"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2021 Nextcloud GmbH and Nextcloud contributors"
SPDX-License-Identifier = "GPL-2.0-or-later"

[[annotations]]
path = ["admin/osx/installer-background.png","admin/osx/installer-background.svg","admin/osx/installer-background_2x.png", "doc/_shared_assets/themes/nextcloud_com/static/img/logo.svg", "doc/_shared_assets/static/logo-blue.pdf","doc/_shared_assets/static/logo-blue.png", "doc/logo-blue.pdf", "theme/talk-app.svg", "theme/*/deck.svg", "theme/*/talk-app.svg","theme/*/wizard-nextcloud.png","theme/*/wizard-nextcloud.svg","theme/*/wizard-nextcloud@2x.png","theme/*/wizard-talk.png","theme/*/wizard-talk.svg","theme/*/wizard-talk@2x.png", "theme/colored/talk-bordered.svg", "theme/colored/icons/Nextcloud-icon-win-folder.svg", "theme/colored/Nextcloud-icon-square.svg", "theme/colored/Nextcloud-icon.svg", "theme/colored/Nextcloud-macOS-icon.svg", "theme/colored/Nextcloud-macOS-sidebar.svg", "theme/colored/Nextcloud-w10startmenu.svg", "theme/colored/Nextcloud-w10starttile.png", "theme/colored/wizard_logo.png", "theme/colored/wizard_logo.svg", "theme/colored/wizard_logo@2x.png"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2016 Nextcloud GmbH"
SPDX-License-Identifier = "LicenseRef-NextcloudTrademarks"

[[annotations]]
path = ["theme/account.svg","theme/add.svg","theme/change.svg","theme/chevron-double-up.svg","theme/close.svg","theme/confirm.svg","theme/copy.svg","theme/delete.svg","theme/external.svg","theme/files.svg","theme/lock-broken.svg","theme/lock-http.svg","theme/lock-https.svg","theme/lock.svg","theme/magnifying-glass.svg","theme/more.svg","theme/network.svg","theme/public.svg","theme/reply.svg","theme/send.svg","theme/settings.svg","theme/share.svg","theme/sync-arrow.svg", "theme/black/account-group.svg","theme/black/clear.svg","theme/black/expand-less-black.svg","theme/black/folder-group.svg","theme/black/search.svg", "theme/colored/add-bordered.svg", "theme/colored/change-bordered.svg", "theme/colored/delete-bordered.svg", "theme/colored/delete.svg", "theme/*/activity.svg", "theme/*/add.svg","theme/*/bell.svg","theme/*/calendar.svg","theme/*/caret-down.svg","theme/*/change.svg","theme/*/close.svg","theme/*/comment.svg","theme/*/confirm.svg","theme/*/control-next.svg","theme/*/control-prev.svg","theme/*/edit.svg","theme/*/email.svg","theme/*/external.png","theme/*/external.svg","theme/*/external@2x.png","theme/*/folder.png","theme/*/folder.svg","theme/*/folder@2x.png","theme/*/more-apps.svg","theme/*/nc-assistant-app.svg","theme/*/settings.svg","theme/*/user.svg","theme/*/wizard-files.png","theme/*/wizard-files.svg","theme/*/wizard-files@2x.png","theme/*/wizard-groupware.png","theme/*/wizard-groupware.svg","theme/*/wizard-groupware@2x.png", "theme/cfapishellext_custom_states/0-locked.svg","theme/cfapishellext_custom_states/1-shared.svg","theme/cfapishellext_custom_states/1024-0-locked.png","theme/cfapishellext_custom_states/1024-1-shared.png","theme/cfapishellext_custom_states/128-0-locked.png","theme/cfapishellext_custom_states/128-1-shared.png","theme/cfapishellext_custom_states/24-0-locked.png","theme/cfapishellext_custom_states/24-1-shared.png","theme/cfapishellext_custom_states/256-0-locked.png","theme/cfapishellext_custom_states/256-1-shared.png","theme/cfapishellext_custom_states/32-0-locked.png","theme/cfapishellext_custom_states/32-1-shared.png","theme/cfapishellext_custom_states/40-0-locked.png","theme/cfapishellext_custom_states/40-1-shared.png","theme/cfapishellext_custom_states/48-0-locked.png","theme/cfapishellext_custom_states/48-1-shared.png","theme/cfapishellext_custom_states/512-0-locked.png","theme/cfapishellext_custom_states/512-1-shared.png","theme/cfapishellext_custom_states/64-0-locked.png","theme/cfapishellext_custom_states/64-1-shared.png"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2018-2025 Google LLC"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = ["doc/scripts/htmlhelp.reg", "doc/scripts/README.rst"]
precedence = "aggregate"
SPDX-FileCopyrightText = "The HTML Help Project"
SPDX-License-Identifier = "LGPL-2.1-only"

[[annotations]]
path = ["doc/_shared_assets/themes/nextcloud_com/static/bootstrap-3.1.0/**", "doc/_shared_assets/themes/nextcloud_release/static/bootstrap**"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2011-2014 Twitter, Inc (now X Corp.)"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = ["doc/_shared_assets/themes/bootstrap/**"]
precedence = "aggregate"
SPDX-FileCopyrightText = "Kyle Finley, Twitter Bootstrap project"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = ["doc/_shared_assets/themes/nextcloud_com/static/bootstrap-sphinx.*", "doc/_shared_assets/themes/nextcloud_com/globaltoc.html", "doc/_shared_assets/themes/nextcloud_com/layout.html", "doc/_shared_assets/themes/nextcloud_com/localtoc.html", "doc/_shared_assets/themes/nextcloud_com/navbar-2.html", "doc/_shared_assets/themes/nextcloud_com/navbar.html", "doc/_shared_assets/themes/nextcloud_com/navbarsearchbox.html", "doc/_shared_assets/themes/nextcloud_com/navbartoc.html", "doc/_shared_assets/themes/nextcloud_com/relations.html", "doc/_shared_assets/themes/nextcloud_com/searchbox.html", "doc/_shared_assets/themes/nextcloud_com/sourcelink.html", "doc/_shared_assets/themes/nextcloud_com/static/main.min.css", "doc/_shared_assets/themes/nextcloud_com/static/styles.css", "doc/_shared_assets/themes/nextcloud_com/theme.conf", "doc/_shared_assets/themes/nextcloud_release/globaltoc.html", "doc/_shared_assets/themes/nextcloud_release/layout.html", "doc/_shared_assets/themes/nextcloud_release/localtoc.html", "doc/_shared_assets/themes/nextcloud_release/navbar-2.html", "doc/_shared_assets/themes/nextcloud_release/navbar.html", "doc/_shared_assets/themes/nextcloud_release/navbarsearchbox.html", "doc/_shared_assets/themes/nextcloud_release/navbartoc.html", "doc/_shared_assets/themes/nextcloud_release/relations.html", "doc/_shared_assets/themes/nextcloud_release/searchbox.html", "doc/_shared_assets/themes/nextcloud_release/sourcelink.html", "doc/_shared_assets/themes/nextcloud_release/static/main.min.css", "doc/_shared_assets/themes/nextcloud_release/static/styles.css", "doc/_shared_assets/themes/nextcloud_release/theme.conf"]
precedence = "aggregate"
SPDX-FileCopyrightText = "Sphinx Bootstrap Theme project"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = ["doc/_shared_assets/themes/nextcloud_release/static/fonts/fontawesome-webfont.*", "doc/_shared_assets/themes/nextcloud_com/static/fonts/fontawesome-webfont.*"]
precedence = "aggregate"
SPDX-FileCopyrightText = "Font Awesome project"
SPDX-License-Identifier = "OFL-1.1"

[[annotations]]
path = ["doc/_shared_assets/themes/nextcloud_release/static/fonts/OpenSans-*.*", "doc/_shared_assets/themes/nextcloud_com/static/fonts/OpenSans-*.*"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2020 The Open Sans Project Authors"
SPDX-License-Identifier = "OFL-1.1"

[[annotations]]
path = ["doc/_shared_assets/themes/nextcloud_release/static/jquery.js", "doc/_shared_assets/themes/nextcloud_com/static/js/jquery-*.js", "doc/_shared_assets/themes/nextcloud_release/static/js/jquery-*.js"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2014 jQuery Project Authors"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = ["doc/_shared_assets/static/social/mail.*", "doc/_shared_assets/static/social/rss.*", "doc/_shared_assets/static/social/rss.*.", "doc/_shared_assets/themes/nextcloud_com/static/img/social/mail*", "doc/_shared_assets/themes/nextcloud_com/static/img/social/rss.*", "doc/_shared_assets/themes/nextcloud_release/static/img/social/mail.*", "doc/_shared_assets/themes/nextcloud_release/static/img/social/rss*", "doc/_shared_assets/themes/nextcloud_release/static/img/note.svg", "doc/_shared_assets/themes/nextcloud_release/static/img/note_pencil.svg", "doc/_shared_assets/themes/nextcloud_com/static/img/note_pencil.svg"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2016 Nextcloud GmbH and Nextcloud contributors"
SPDX-License-Identifier = "AGPL-3.0-or-later"

[[annotations]]
path = ["doc/_shared_assets/static/social/diaspora.*", "doc/_shared_assets/static/social/diasporaround.*", "doc/_shared_assets/themes/nextcloud_com/static/img/social/diaspora.*", "doc/_shared_assets/themes/nextcloud_com/static/img/social/diasporaround.*", "doc/_shared_assets/themes/nextcloud_release/static/img/social/diaspora.*", "doc/_shared_assets/themes/nextcloud_release/static/img/social/diasporaround.*"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2025 Diaspora"
SPDX-License-Identifier = "LicenseRef-DiasporaTrademarks"

[[annotations]]
path = ["doc/_shared_assets/static/social/facebook.png", "doc/_shared_assets/themes/nextcloud_com/static/img/social/facebook.*", "doc/_shared_assets/themes/nextcloud_release/static/img/social/facebook.*"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 Meta"
SPDX-License-Identifier = "LicenseRef-FacebookTrademarks"

[[annotations]]
path = ["doc/_shared_assets/static/social/youtube.svg", "doc/_shared_assets/static/social/googleplus.png", "doc/_shared_assets/themes/nextcloud_com/static/img/social/googleplus.*", "doc/_shared_assets/themes/nextcloud_com/static/img/social/youtube.*",  "doc/_shared_assets/themes/nextcloud_release/static/img/social/googleplus.*", "doc/_shared_assets/themes/nextcloud_release/static/img/social/youtube.*"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 Google LLC."
SPDX-License-Identifier = "LicenseRef-GoogleTrademarks"

[[annotations]]
path = ["doc/_shared_assets/themes/nextcloud_release/static/img/glyphicons-halflings*.png"]
precedence = "aggregate"
SPDX-FileCopyrightText = "Jan Kovařík Glyphicons"
SPDX-License-Identifier = "LicenseRef-GlyphiconsRegularLicense"

[[annotations]]
path = ["doc/_shared_assets/themes/nextcloud_com/static/img/home/background3.jpg"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 Nextcloud GmbH"
SPDX-License-Identifier = "CC-BY-SA-4.0"

[[annotations]]
path = ["doc/_shared_assets/themes/nextcloud_com/static/img/warning.svg", "doc/_shared_assets/themes/nextcloud_release/static/img/note.svg", "doc/_shared_assets/themes/nextcloud_release/static/img/todo.svg", "doc/_shared_assets/themes/nextcloud_release/static/img/warning.svg", "doc/_shared_assets/themes/nextcloud_release/static/img/social/youtube.*"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2018-2024 Google LLC."
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = ["doc/_shared_assets/static/social/twitter.svg", "doc/_shared_assets/static/social/twitterround.png", "doc/_shared_assets/themes/nextcloud_com/static/img/social/twitter.*", "doc/_shared_assets/themes/nextcloud_com/static/img/social/twitterround.*", "doc/_shared_assets/themes/nextcloud_release/static/img/social/twitter.*", "doc/_shared_assets/themes/nextcloud_release/static/img/social/twitterround.*"]
precedence = "aggregate"
SPDX-FileCopyrightText = "X Corp."
SPDX-License-Identifier = "LicenseRef-XTrademarks"
