# SPDX-FileCopyrightText: 2023 Nextcloud GmbH and Nextcloud contributors
# SPDX-License-Identifier: GPL-2.0-or-later
name: Check translations

on:
  pull_request:
    types: [opened, synchronize, reopened]

# Declare default permissions as read only.
permissions: read-all

jobs:
  checkTranslations:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Check German
        run: |
          [[ $(grep "Benötigt keine Übersetzung" translations/client_de.ts -c) -gt 0 ]] && exit 1 || exit 0
