name: SonarCloud analysis
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, reopened]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container: ghcr.io/nextcloud/continuous-integration-client:client-5.15-4
    env:
      SONAR_SERVER_URL: "https://sonarcloud.io"
      BUILD_WRAPPER_OUT_DIR: build_wrapper_output_directory # Directory where build-wrapper output will be placed
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis

      - name: Restore cache
        uses: actions/cache@v2
        with:
          path: /cache
          key: ${{ runner.os }}

      - name: Run build-wrapper
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_COMPILER=gcc-10 -DCMAKE_CXX_COMPILER=g++-10 -DBUILD_UPDATER=ON -DBUILD_TESTING=1 -DBUILD_COVERAGE=ON
          build-wrapper-linux-x86-64 --out-dir ${{ env.BUILD_WRAPPER_OUT_DIR }} make -j 2
      - name: Run tests
        run: |
          cd build
          useradd -m -s /bin/bash test
          chown -R test:test .
          su -c 'xvfb-run ctest --output-on-failure --output-junit testResult.xml' test
      - name: Generate coverage report
        run: |
          cd build
          su -c 'ctest -T Coverage' test
      - name: Run sonar-scanner
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          cp sonar-project.properties build
          cd build
          sonar-scanner --define sonar.host.url="${{ env.SONAR_SERVER_URL }}" --define sonar.cfamily.build-wrapper-output="${{ env.BUILD_WRAPPER_OUT_DIR }}"
    
  build-on-windows:
    name: Build-on-windows
    runs-on: windows-2019
    env:
      SONAR_SERVER_URL: "https://sonarcloud.io"
      BUILD_WRAPPER_OUT_DIR: build_wrapper_output_directory # Directory where build-wrapper output will be placed
      CRAFT_TARGET: windows-msvc2019_64-cl
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis

      - name: Restore cache
        uses: actions/cache@v2
        with:
          path: /cache
          key: ${{ runner.os }}

      - name: Install
        shell: pwsh
        run: |
          choco install opencppcoverage
          & cmd /C "git clone -q --depth=1 https://invent.kde.org/packaging/craftmaster.git C:\CraftMaster\CraftMaster 2>&1"
          
          function craft() {
              python "C:\CraftMaster\CraftMaster\CraftMaster.py" --verbose --config "${{ github.workspace }}\appveyor.ini" --variables "APPVEYOR_BUILD_FOLDER=${{ github.workspace }}" --target ${{ env.CRAFT_TARGET }} -c $args
          }
          
          craft --add-blueprint-repository [git]https://github.com/nextcloud/desktop-client-blueprints.git
          craft craft
          craft --install-deps nextcloud-client
          craft nsis
          
      - name: Compile
        shell: pwsh
        run: |
          function craft() {
              python "C:\CraftMaster\CraftMaster\CraftMaster.py" --verbose --config "${{ github.workspace }}\appveyor.ini" --variables "APPVEYOR_BUILD_FOLDER=${{ github.workspace }}" --target ${{ env.CRAFT_TARGET }} -c $args
          }
          
          craft --src-dir ${{ github.workspace }} nextcloud-client
          
      - name: Run tests
        shell: pwsh
        run: |
          function runTests() {
              cmd /C "echo %PATH%"
              $buildFolder = "C:/CraftMaster/windows-msvc2019_64-cl/build/nextcloud-client/work/build"
              cd "$buildFolder/bin"
        
              echo "sources at: ${{ github.workspace }}"
        
              $testFiles = Get-ChildItem . -Recurse | where {$_.name -clike "*Test.exe"} | select -expand name
        
              $totalTests = $testFiles.count
        
              $counter = 0
        
              $previousCov = "";
        
              foreach ($testFile in $testFiles) {
                  $counter += 1
                  if($counter -ne $totalTests) {
                      & OpenCppCoverage.exe --sources ${{ github.workspace }} --modules C:\CraftMaster\windows-msvc2019_64-cl\build\nextcloud-client\work\build\bin\*.dll* --export_type binary:$testFile.cov $testFile
                      $previousCov += "--input_coverage=$testFile.cov "
                  } else {
                      $runLastTestAndMergeReport = "OpenCppCoverage.exe --sources ${{ github.workspace }} --modules C:\CraftMaster\windows-msvc2019_64-cl\build\nextcloud-client\work\build\bin\*.dll* --export_type cobertura:$buildFolder/test_coverage_cobertura/test_coverage_final.xml --export_type html:$buildFolder/test_coverage_html" + " $previousCov" + $testFile
                      Invoke-Expression $runLastTestAndMergeReport
                  }
              }
          }
          
          runTests